"""add roles and job market tables

Revision ID: 1bfd7b55aa63
Revises: 9993a3414c2b
Create Date: 2026-03-03 21:08:43.161194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1bfd7b55aa63'
down_revision: Union[str, Sequence[str], None] = '9993a3414c2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_postings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('employment_type', sa.String(length=80), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('url', sa.String(length=800), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_postings_posted_at'), 'job_postings', ['posted_at'], unique=False)
    op.create_index(op.f('ix_job_postings_source'), 'job_postings', ['source'], unique=False)
    op.create_index('ix_job_postings_source_external_id', 'job_postings', ['source', 'external_id'], unique=False)
    op.create_index('uq_job_postings_source_external_id_active', 'job_postings', ['source', 'external_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('seniority', sa.String(length=50), nullable=True),
    sa.Column('role_embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_category'), 'roles', ['category'], unique=False)
    op.create_index(op.f('ix_roles_normalized_name'), 'roles', ['normalized_name'], unique=False)
    op.create_index('uq_roles_normalized_name_active', 'roles', ['normalized_name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('job_posting_skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_posting_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('extraction_method', sa.String(length=50), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_posting_id', 'skill_id', name='uq_job_posting_skills_job_posting_id_skill_id')
    )
    op.create_index(op.f('ix_job_posting_skills_job_posting_id'), 'job_posting_skills', ['job_posting_id'], unique=False)
    op.create_index(op.f('ix_job_posting_skills_skill_id'), 'job_posting_skills', ['skill_id'], unique=False)
    op.create_table('role_skill_demand',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('demand_percent', sa.Float(), nullable=False),
    sa.Column('trend_delta', sa.Float(), nullable=True),
    sa.Column('market_last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_skill_demand_market_last_updated'), 'role_skill_demand', ['market_last_updated'], unique=False)
    op.create_index(op.f('ix_role_skill_demand_role_id'), 'role_skill_demand', ['role_id'], unique=False)
    op.create_index(op.f('ix_role_skill_demand_skill_id'), 'role_skill_demand', ['skill_id'], unique=False)
    op.create_index('uq_role_skill_demand_role_id_skill_id_active', 'role_skill_demand', ['role_id', 'skill_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('role_skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('importance_weight', sa.Float(), server_default=sa.text('1.0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'skill_id', name='uq_role_skills_role_id_skill_id')
    )
    op.create_index(op.f('ix_role_skills_role_id'), 'role_skills', ['role_id'], unique=False)
    op.create_index(op.f('ix_role_skills_skill_id'), 'role_skills', ['skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_skills_skill_id'), table_name='role_skills')
    op.drop_index(op.f('ix_role_skills_role_id'), table_name='role_skills')
    op.drop_table('role_skills')
    op.drop_index('uq_role_skill_demand_role_id_skill_id_active', table_name='role_skill_demand', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_role_skill_demand_skill_id'), table_name='role_skill_demand')
    op.drop_index(op.f('ix_role_skill_demand_role_id'), table_name='role_skill_demand')
    op.drop_index(op.f('ix_role_skill_demand_market_last_updated'), table_name='role_skill_demand')
    op.drop_table('role_skill_demand')
    op.drop_index(op.f('ix_job_posting_skills_skill_id'), table_name='job_posting_skills')
    op.drop_index(op.f('ix_job_posting_skills_job_posting_id'), table_name='job_posting_skills')
    op.drop_table('job_posting_skills')
    op.drop_index('uq_roles_normalized_name_active', table_name='roles', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_roles_normalized_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_category'), table_name='roles')
    op.drop_table('roles')
    op.drop_index('uq_job_postings_source_external_id_active', table_name='job_postings', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_job_postings_source_external_id', table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_source'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_posted_at'), table_name='job_postings')
    op.drop_table('job_postings')
    # ### end Alembic commands ###
