"""add roadmap and tracking tables

Revision ID: 90521e406026
Revises: 1bfd7b55aa63
Create Date: 2026-03-03 21:20:09.879970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90521e406026'
down_revision: Union[str, Sequence[str], None] = '1bfd7b55aa63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=800), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=True),
    sa.Column('skill_id', sa.UUID(), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('difficulty_level', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_resource_type'), 'resources', ['resource_type'], unique=False)
    op.create_index(op.f('ix_resources_skill_id'), 'resources', ['skill_id'], unique=False)
    op.create_table('roadmaps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('generation_version', sa.String(length=50), nullable=True),
    sa.Column('created_reason', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmaps_is_active'), 'roadmaps', ['is_active'], unique=False)
    op.create_index(op.f('ix_roadmaps_role_id'), 'roadmaps', ['role_id'], unique=False)
    op.create_index(op.f('ix_roadmaps_user_id'), 'roadmaps', ['user_id'], unique=False)
    op.create_table('roadmap_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('roadmap_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('skill_id', sa.UUID(), nullable=True),
    sa.Column('week_number', sa.Integer(), nullable=True),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('estimated_hours', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmap_steps_roadmap_id'), 'roadmap_steps', ['roadmap_id'], unique=False)
    op.create_index(op.f('ix_roadmap_steps_step_order'), 'roadmap_steps', ['step_order'], unique=False)
    op.create_index(op.f('ix_roadmap_steps_week_number'), 'roadmap_steps', ['week_number'], unique=False)
    op.create_table('user_resource_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'not_started'"), nullable=False),
    sa.Column('progress_percent', sa.Float(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'resource_id', name='uq_user_resource_progress_user_id_resource_id')
    )
    op.create_index(op.f('ix_user_resource_progress_resource_id'), 'user_resource_progress', ['resource_id'], unique=False)
    op.create_index(op.f('ix_user_resource_progress_user_id'), 'user_resource_progress', ['user_id'], unique=False)
    op.create_table('weekly_checkins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('roadmap_id', sa.UUID(), nullable=True),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('progress_percent', sa.Float(), nullable=True),
    sa.Column('reflection_notes', sa.Text(), nullable=True),
    sa.Column('confidence_delta', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'week_start_date', name='uq_weekly_checkins_user_week')
    )
    op.create_index(op.f('ix_weekly_checkins_user_id'), 'weekly_checkins', ['user_id'], unique=False)
    op.create_index(op.f('ix_weekly_checkins_week_start_date'), 'weekly_checkins', ['week_start_date'], unique=False)
    op.create_table('roadmap_step_completion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('roadmap_step_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'not_started'"), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['roadmap_step_id'], ['roadmap_steps.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'roadmap_step_id', name='uq_roadmap_step_completion_user_id_roadmap_step_id')
    )
    op.create_index(op.f('ix_roadmap_step_completion_roadmap_step_id'), 'roadmap_step_completion', ['roadmap_step_id'], unique=False)
    op.create_index(op.f('ix_roadmap_step_completion_status'), 'roadmap_step_completion', ['status'], unique=False)
    op.create_index(op.f('ix_roadmap_step_completion_user_id'), 'roadmap_step_completion', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roadmap_step_completion_user_id'), table_name='roadmap_step_completion')
    op.drop_index(op.f('ix_roadmap_step_completion_status'), table_name='roadmap_step_completion')
    op.drop_index(op.f('ix_roadmap_step_completion_roadmap_step_id'), table_name='roadmap_step_completion')
    op.drop_table('roadmap_step_completion')
    op.drop_index(op.f('ix_weekly_checkins_week_start_date'), table_name='weekly_checkins')
    op.drop_index(op.f('ix_weekly_checkins_user_id'), table_name='weekly_checkins')
    op.drop_table('weekly_checkins')
    op.drop_index(op.f('ix_user_resource_progress_user_id'), table_name='user_resource_progress')
    op.drop_index(op.f('ix_user_resource_progress_resource_id'), table_name='user_resource_progress')
    op.drop_table('user_resource_progress')
    op.drop_index(op.f('ix_roadmap_steps_week_number'), table_name='roadmap_steps')
    op.drop_index(op.f('ix_roadmap_steps_step_order'), table_name='roadmap_steps')
    op.drop_index(op.f('ix_roadmap_steps_roadmap_id'), table_name='roadmap_steps')
    op.drop_table('roadmap_steps')
    op.drop_index(op.f('ix_roadmaps_user_id'), table_name='roadmaps')
    op.drop_index(op.f('ix_roadmaps_role_id'), table_name='roadmaps')
    op.drop_index(op.f('ix_roadmaps_is_active'), table_name='roadmaps')
    op.drop_table('roadmaps')
    op.drop_index(op.f('ix_resources_skill_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_resource_type'), table_name='resources')
    op.drop_table('resources')
    # ### end Alembic commands ###
